---
- name: "stop rsyslogd"
  community.docker.docker_compose_v2:
    project_src: /etc/contrail/rsyslogd
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
