# We only send SIGQUIT to the vrouter-agent, because there is no
# corresponding handler in other vrouter containers
- name: kill vrouter-agent docker container
  shell: "docker-compose -f /etc/contrail/vrouter/docker-compose.yaml kill -s SIGQUIT vrouter-agent"

- name: get id of vrouter-agent docker container
  shell: "docker-compose -f /etc/contrail/vrouter/docker-compose.yaml ps -q vrouter-agent"
  register: vrouter_agent_container_output

- set_fact: vrouter_agent_container={{ vrouter_agent_container_output.stdout }}

- name: check if container does not running
  shell: "{% raw %}docker inspect --format='{{json .State.Status}}'{% endraw %} {{ vrouter_agent_container }}"
  register: vrouter_agent_container_status
  retries: 10
  until: vrouter_agent_container_status.rc != 0 or vrouter_agent_container_status.stdout != "\"running\""
  ignore_errors: yes

- name: remove all built vrouter.ko on RedHat families
  shell: "rm -rf /lib/modules/*/kernel/net/vrouter/vrouter.ko"
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- name: remove all built vrouter.ko on Debian families
  shell: "rm -rf /lib/modules/*/updates/dkms/vrouter.ko"
  when: ansible_os_family == 'Debian'

# and remove compose artefacts - otherwise we catch error exception on update
- name: "stop vrouter"
  community.docker.docker_compose_v2:
    project_src: /etc/contrail/vrouter
    state: absent
  environment:
    DOCKER_CLIENT_TIMEOUT: '120'
    COMPOSE_HTTP_TIMEOUT: '120'
