# ansible-playbook -i inventory/ playbook/install_openstack.yml
#
- name: Create container host group for OpenStack
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Expose instances
      set_fact:
        instances: "{{ instances }}"
      when: hostvars['localhost']['instances'] is undefined
    - name: Expose global_configuration
      set_fact:
        global_configuration: "{{ global_configuration | default({}) }}"
      when: hostvars['localhost']['global_configuration'] is undefined
  roles:
    - opensdn_deployer
    - openstack_deployer
  vars_files:
    - "{{ config_file }}"
  tags: always

- hosts: openstack_nodes
  gather_facts: yes
  roles:
    - name: Generate openstack configurations
      role: openstack
      tags: always
  vars_files:
    - "{{ hostvars['localhost'].config_file }}"
  vars:
    - container_registry: "{{ hostvars['localhost'].container_registry }}"
    - contrail_version_tag: "{{ hostvars['localhost'].contrail_version_tag }}"
    - config_nodes_list: "{{ hostvars['localhost'].config_nodes_list }}"
    - analytics_nodes_list: "{{ hostvars['localhost'].analytics_nodes_list }}"
    - openstack_nodes_list: "{{ hostvars['localhost'].openstack_nodes_list }}"
    - webui_nodes_list: "{{ hostvars['localhost'].webui_nodes_list }}"
  tasks:
  - name: Import group variables
    no_log: True
    include_vars:
      dir: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/group_vars"
      extensions: ['yml']
    tags: always

  - name: Import global variables
    no_log: True
    include_vars:
      dir: "{{ playbook_dir }}/../../contrail-kolla-ansible/etc/kolla"
      extensions: ['yml']
      ignore_files:
        - passwords.yml.original
        - globals.yml.original
    tags: always

  - name: set tmphost
    set_fact:
      tmp_host: "{{ inventory_hostname }}"
    tags: always

  - stat:
      path: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/host_vars/{{ tmp_host }}.yml"
    register: st
    delegate_to: localhost
    tags: always

  - name: Import host variables
    include_vars:
      file: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/host_vars/{{ inventory_hostname }}.yml"
    when: st.stat.exists is defined and st.stat.exists
    tags: always

  - name: Set docker environment variable DOCKER_CLIENT_TIMEOUT
    lineinfile:
      path: /etc/environment
      regexp: '^DOCKER_CLIENT_TIMEOUT='
      line: 'DOCKER_CLIENT_TIMEOUT=120'

  - name: Set docker environment variable COMPOSE_HTTP_TIMEOUT 
    lineinfile:
      path: /etc/environment
      regexp: '^COMPOSE_HTTP_TIMEOUT='
      line: 'COMPOSE_HTTP_TIMEOUT=120'

# include playbook may not be trivial as the playbooks will not have access to
# the global variables. To avoid changes to kolla playbooks, including the role
# directly
- name: Create certificates for haproxy
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - kolla_config: "{{ hostvars['localhost'].get('kolla_config', None) }}"
  vars_files:
    - "{{ config_file }}"
  pre_tasks:
    - name: Import group variables
      no_log: True
      include_vars:
        dir: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/group_vars"
        extensions: ['yml']
    - name: Import global variables
      no_log: True
      include_vars:
        dir: "{{ playbook_dir }}/../../contrail-kolla-ansible/etc/kolla"
        extensions: ['yml']
        ignore_files:
          - passwords.yml.original
          - globals.yml.original
    - name: Generate certificates for openstack
      include_role:
        name: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/roles/certificates"
      when:
        - kolla_config is defined
        - kolla_config.kolla_globals is defined
        - kolla_config.kolla_globals.generate_self_signed_certs is defined
        - kolla_config.kolla_globals.generate_self_signed_certs|bool

- name: Calculate the deleted nodes list
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - kolla_config: "{{ hostvars['localhost'].get(kolla_config, None) }}"
  vars_files:
    - "{{ config_file }}"
  pre_tasks:
    - name: Expose instances
      set_fact:
        instances: "{{ instances }}"
      when: hostvars['localhost']['instances'] is undefined
    - name: Expose global_configuration
      set_fact:
        global_configuration: "{{ global_configuration | default({}) }}"
      when: hostvars['localhost']['global_configuration'] is undefined
  tasks:
    - include_role:
        name: openstack_deployer
        tasks_from: cluster_node_role_lists
      when:
        - hostvars['localhost'].global_configuration.ENABLE_DESTROY | default('True') | bool
  tags: nova

# TODO: move this playbook to local roles from kolla
#- name: Deregister deleted Openstack Computes
#  import_playbook: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/deregister_compute.yml"
#  vars:
#    dir: "{{ playbook_dir }}/../../contrail-kolla-ansible/etc/kolla"
#    extensions: ['yml']
#    deleted_nodes_dict: "{{ hostvars['localhost'].deleted_nodes_dict }}"
#    global_configuration: "{{ hostvars['localhost'].global_configuration }}"
#  when:
#    - hostvars['localhost'].global_configuration.ENABLE_DESTROY | default('True') | bool
#  tags: nova

- name: Destroy Deleted Openstack Nodes
  import_playbook: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/destroy.yml"
  vars:
    dir: "{{ playbook_dir }}/../../contrail-kolla-ansible/etc/kolla"
    extensions: ['yml']
    deleted_nodes_dict: "{{ hostvars['localhost'].deleted_nodes_dict }}"
    contrail_cleanup: true
    destroy_include_images: "{{ enable_destroy_images | default('no') }}"
    global_configuration: "{{ hostvars['localhost'].global_configuration }}"
  when:
    - hostvars['localhost'].global_configuration.ENABLE_DESTROY | default('True') | bool
    - hostvars['localhost'].deleted_nodes_dict.keys() | length > 0
    - inventory_hostname in hostvars['localhost'].deleted_nodes_dict.values()
  tags: nova

- import_playbook: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/site.yml"
  vars:
    action: deploy
    kolla_action: deploy

# Disabled: post-deploy-contrail.yml is not compatible with ansible-core >=2.15.
# The 'extensions' parameter of include_vars no longer accepts a list value,
# which causes all include_vars tasks in that playbook to fail at runtime.
# The post-deploy step is documented in the README under "After Installation"
# and should be run manually from /root/contrail-kolla-ansible.
#
# - import_playbook: "{{ playbook_dir }}/../../contrail-kolla-ansible/ansible/post-deploy-contrail.yml"

- name: Correct noVNC proxy URL on compute nodes
  hosts: compute
  gather_facts: no
  become: yes
  # Kolla sets novncproxy_base_url to the controller's internal IP address.
  # On NIPA Cloud, users reach the console through the controller's floating IP,
  # so the URL must be updated before noVNC sessions will work.
  # Pass the floating IP at runtime with: -e novnc_public_ip=<FLOATING_IP>
  pre_tasks:
    - name: Verify novnc_public_ip is defined
      ansible.builtin.fail:
        msg: >
          Required variable 'novnc_public_ip' is not set.
          Re-run with: -e novnc_public_ip=<CONTROLLER_FLOATING_IP>
      when: novnc_public_ip is not defined or novnc_public_ip | length == 0
  tasks:
    - name: Replace internal controller IP with public IP in nova.conf
      ansible.builtin.replace:
        path: /etc/kolla/nova-compute/nova.conf
        regexp: '(novncproxy_base_url\s*=\s*http://)[^:]+(:.*)'
        replace: '\g<1>{{ novnc_public_ip }}\g<2>'
      notify: Restart nova_compute

  handlers:
    - name: Restart nova_compute
      community.docker.docker_container:
        name: nova_compute
        state: started
        restart: yes
